/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import control.ControleVisao;
import domain.Cliente;
import domain.Produto;
import domain.state.aluguel.Fechado;
import domain.state.produto.EmLoja;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liviaaurich
 */
public class JDGRegistrarReserva extends javax.swing.JDialog {

    private static JDGRegistrarReserva UNIQUEINSTANCE;

    private final ControleVisao controladorVisao;
    private List<Produto> resultadoBusca;
    private Cliente cliente;

    private JDGRegistrarReserva(java.awt.Frame parent, boolean modal, ControleVisao controlador) {
        super(parent, modal);
        initComponents();
        controladorVisao = controlador;
    }

    public static synchronized JDGRegistrarReserva getInstance(java.awt.Frame parent, boolean modal, ControleVisao controlador) {
        if (UNIQUEINSTANCE == null) {
            UNIQUEINSTANCE = new JDGRegistrarReserva(parent, modal, controlador);
        }

        UNIQUEINSTANCE.setModal(modal);
        return UNIQUEINSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrarReserva = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftxtDataDevolucao = new javax.swing.JFormattedTextField();
        ftxtDataRetirada = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Reserva");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Em Loja"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tblRegistrarReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Nome", "Tamanho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistrarReserva.setEnabled(false);
        tblRegistrarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrarReservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistrarReserva);
        if (tblRegistrarReserva.getColumnModel().getColumnCount() > 0) {
            tblRegistrarReserva.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblRegistrarReserva.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jPanel2.add(jScrollPane1);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Total = R$");

        lblValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 51, 51));
        lblValor.setText("0,0");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        btnBuscarCliente.setText("...");
        btnBuscarCliente.setPreferredSize(new java.awt.Dimension(23, 23));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ic_add_circle_outline_48px.svg.png"))); // NOI18N
        btnCadastrarCliente.setEnabled(false);
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        txtNomeCliente.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Retirada");

        jLabel2.setText("Devolucao");

        try {
            ftxtDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtDataRetirada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValor)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ftxtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReservar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(jLabel1)
                    .addComponent(ftxtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCancelar)
                    .addComponent(ftxtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tblRegistrarReserva.getModel();
        tabela.setRowCount(0);

        tblRegistrarReserva.setEnabled(false);
        btnReservar.setEnabled(false);
        btnCadastrarCliente.setEnabled(false);
        lblValor.setText("0,0");

        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        controladorVisao.cadastroCliente();
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void tblRegistrarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrarReservaMouseClicked

        Double valor = 0.0;
        int posicoes[] = tblRegistrarReserva.getSelectedRows();
        for (int i = 0; i < posicoes.length; i++) {
            valor += ((Produto) resultadoBusca.get(posicoes[i])).getValorDiaria();
        }

        lblValor.setText(String.valueOf(valor));

    }//GEN-LAST:event_tblRegistrarReservaMouseClicked

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed

        List<Produto> listaProdutos = new ArrayList<>();

        int posicoes[] = tblRegistrarReserva.getSelectedRows();
        for (int i = 0; i < posicoes.length; i++) {
            listaProdutos.add((Produto) resultadoBusca.get(posicoes[i]));
        }

        String valorTotal = lblValor.getText();

        if (posicoes.length != 0) {
            try {
                controladorVisao.getControleDominio().aluguelCreate(listaProdutos, cliente,
                        ftxtDataRetirada.getText(), ftxtDataDevolucao.getText(), valorTotal);
                limparTela();
                atualizaTabela();
                JOptionPane.showMessageDialog(this, "Reserva registrada com sucesso.");
                cliente = null;
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Insira uma data válida.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione pelo ao menos um produto.");
        }

    }//GEN-LAST:event_btnReservarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        atualizaTabela();
    }//GEN-LAST:event_formComponentShown

    private void atualizaTabela() {
        DefaultTableModel tabela = (DefaultTableModel) tblRegistrarReserva.getModel();

        tabela.setRowCount(0);

        resultadoBusca = controladorVisao.getControleDominio().produtoReadEstado(EmLoja.getInstance());

        if (!resultadoBusca.isEmpty() || resultadoBusca != null) {
            tblRegistrarReserva.setEnabled(true);
            btnCadastrarCliente.setEnabled(true);
            resultadoBusca.forEach((p) -> {
                tabela.addRow(new Object[]{p.getCategoria(),
                    p.getNome(),
                    p.getTamanho()});
            });
        }
    }

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        cliente = null;
        cliente = controladorVisao.buscaCliente();
        if (controladorVisao.getControleDominio().aluguelReadIndireto(cliente, Fechado.getInstance()).size() > 0) {
            JOptionPane.showMessageDialog(this, "O cliente selecionado já possui um aluguel em aberto / a ser retirado.");
        } else {
            txtNomeCliente.setText(cliente.toString());
            btnReservar.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JFormattedTextField ftxtDataDevolucao;
    private javax.swing.JFormattedTextField ftxtDataRetirada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tblRegistrarReserva;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables

    private void limparTela() {
        ftxtDataDevolucao.setText("");
        ftxtDataRetirada.setText("");
        txtNomeCliente.setText("");
        cliente = null;
        lblValor.setText("00,00");

    }
}
