/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import control.ControleVisao;

/**
 *
 * @author gudeck
 */
public class JFRPrincipal extends javax.swing.JFrame {

    private final ControleVisao controladorVisao;

    public JFRPrincipal(ControleVisao controlador) {
        initComponents();
        controladorVisao = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuiCadastroCliente = new javax.swing.JMenuItem();
        mnuiCadastroCategoria = new javax.swing.JMenuItem();
        mnuiCadastroProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniRegistrarReserva = new javax.swing.JMenuItem();
        mniRegistrarRetirada = new javax.swing.JMenuItem();
        mniRegistrarDevolucao = new javax.swing.JMenuItem();
        mniRegistrarManutenção = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anarriê");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(562, 280));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 280);

        jMenu1.setText("Cadastro");

        mnuiCadastroCliente.setText("Cliente");
        mnuiCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiCadastroCliente);

        mnuiCadastroCategoria.setText("Categoria");
        mnuiCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiCadastroCategoria);

        mnuiCadastroProduto.setText("Produto");
        mnuiCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCadastroProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiCadastroProduto);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Registros");

        mniRegistrarReserva.setText("Reserva");
        mniRegistrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistrarReservaActionPerformed(evt);
            }
        });
        jMenu3.add(mniRegistrarReserva);

        mniRegistrarRetirada.setText("Retirada");
        mniRegistrarRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistrarRetiradaActionPerformed(evt);
            }
        });
        jMenu3.add(mniRegistrarRetirada);

        mniRegistrarDevolucao.setText("Devolução");
        mniRegistrarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistrarDevolucaoActionPerformed(evt);
            }
        });
        jMenu3.add(mniRegistrarDevolucao);

        mniRegistrarManutenção.setText("Manutenção");
        mniRegistrarManutenção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistrarManutençãoActionPerformed(evt);
            }
        });
        jMenu3.add(mniRegistrarManutenção);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Anarrie");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCadastroClienteActionPerformed
        controladorVisao.cadastroCliente();
    }//GEN-LAST:event_mnuiCadastroClienteActionPerformed

    private void mnuiCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCadastroCategoriaActionPerformed
        controladorVisao.cadastroCategoria();
    }//GEN-LAST:event_mnuiCadastroCategoriaActionPerformed

    private void mniRegistrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistrarReservaActionPerformed
        controladorVisao.registrarReserva();
    }//GEN-LAST:event_mniRegistrarReservaActionPerformed

    private void mniRegistrarRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistrarRetiradaActionPerformed
        controladorVisao.registrarRetirada();
    }//GEN-LAST:event_mniRegistrarRetiradaActionPerformed

    private void mniRegistrarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistrarDevolucaoActionPerformed
        controladorVisao.registrarDevolucao();
    }//GEN-LAST:event_mniRegistrarDevolucaoActionPerformed

    private void mniRegistrarManutençãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistrarManutençãoActionPerformed
        controladorVisao.registrarAvaliacaoProduto();
    }//GEN-LAST:event_mniRegistrarManutençãoActionPerformed

    private void mnuiCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCadastroProdutoActionPerformed
        controladorVisao.cadastroProduto();
    }//GEN-LAST:event_mnuiCadastroProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mniRegistrarDevolucao;
    private javax.swing.JMenuItem mniRegistrarManutenção;
    private javax.swing.JMenuItem mniRegistrarReserva;
    private javax.swing.JMenuItem mniRegistrarRetirada;
    private javax.swing.JMenuItem mnuiCadastroCategoria;
    private javax.swing.JMenuItem mnuiCadastroCliente;
    private javax.swing.JMenuItem mnuiCadastroProduto;
    // End of variables declaration//GEN-END:variables
}
